pipeline {
    agent {
        docker {
            image 'node:20'
        }
    }

    environment {
        // Docker Hub credentials ID (configure in Jenkins -> Credentials)
        DOCKER_HUB_CREDENTIALS = 'dockerhub-credentials'
        DOCKER_HUB_USER = 'ghandrisemh'
        IMAGE_NAME = 'ghandrisemh/angular-devops'
        IMAGE_TAG = 'latest'

        // SonarQube installation name (configure in Jenkins -> Manage Jenkins -> Configure System)
        SONARQUBE_ENV = 'SonarQube'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/TyreX6/angular-devops.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build & Test') {
            steps {
                sh 'npm run build-prod'
            }
        }

        stage('SonarQube analysis') {
            environment {
                scannerHome = tool 'SonarQube'   // Defined in Jenkins Global Tool Config
            }
            steps {
                withSonarQubeEnv('SonarQube') {         // Defined in Jenkins "Configure System"
                    sh """
                        ${scannerHome}/bin/sonar-scanner \
                          -Dsonar.projectKey=angular-devops \
                          -Dsonar.projectName=angular-devops \
                          -Dsonar.sources=src \
                          -Dsonar.tests=src \
                          -Dsonar.typescript.tsconfigPath=tsconfig.json \
                          -Dsonar.exclusions=node_modules/** \
                          -Dsonar.test.inclusions=**/*.spec.ts \
                          -Dsonar.testExecutionReportPaths=test-reports/ut_report.xml
                    """
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv("${SONARQUBE_ENV}") {
                  sh "chmod 777 /var/jenkins_home/workspace/angular-devops-ci/node_modules/sonar-scanner/bin/sonar-scanner"
                  sh """
                  npm run sonar -- -Dsonar.projectKey=angular-devops -Dsonar.host.url=http://localhost:9000 -Dsonar.login=${SONAR_AUTH_TOKEN}
                        """
                }
            }
        }


        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: "${DOCKER_HUB_CREDENTIALS}", usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
                        sh "docker push ${IMAGE_NAME}:${IMAGE_TAG}"
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
