pipeline {
    agent any
    environment {
        // Docker Hub credentials ID (configure in Jenkins -> Credentials)
        DOCKER_HUB_CREDENTIALS = 'dockerhub-credentials'
        DOCKER_HUB_USER = 'ghandrisemh'
        IMAGE_NAME = 'ghandrisemh/angular-devops'
        IMAGE_TAG = 'latest'
        // SonarQube installation name (configure in Jenkins -> Manage Jenkins -> Configure System)
        SONARQUBE_ENV = 'SonarQube'
    }
    stages {
        stage('Install Dependencies') {
            agent {
                docker {
                    image 'node:20'
                }
            }
            steps {
                sh 'npm install'
            }
        }
        stage('Build & Test') {
            agent {
                docker {
                    image 'node:20'
                }
            }
            steps {
                sh 'npm run build-prod'
                stash includes: 'dist/**', name: 'angular-devops-dist'
            }
        }
        stage('SonarQube analysis') {
            agent {
                docker {
                    image 'sonarsource/sonar-scanner-cli:latest'
                    args '-u root --network=devops_network'
                    // -u root (run as root inside container if needed)
                    // --network=host (so container can reach SonarQube on host machine)
                }
            }
            environment {
                SONAR_HOST_URL = 'http://sonarqube:9000'  // change if needed
                SONAR_TOKEN = credentials('sonarqube')  // Jenkins credential ID
            }
            when {
                anyOf {
                    branch 'main'
                    branch 'develop'
                    branch pattern: "feature/.*", comparator: "REGEXP"
                }
            }
            steps {
                input message: "Scan the project?", ok: "Scan now"
                echo "🚀 Scanning the project"
                sh """
                sonar-scanner \
                      -Dsonar.projectKey=angular-devops \
                      -Dsonar.projectName=angular-devops \
                      -Dsonar.sources=src \
                      -Dsonar.exclusions=node_modules/** \
                      -Dsonar.typescript.tsconfigPath=tsconfig.json \
                      -Dsonar.host.url=${SONAR_HOST_URL} \
                      -Dsonar.login=${SONAR_TOKEN}
                      """
            }
        }
        stage('Build Docker Image') {
            steps {
                unstash 'angular-devops-dist'
                script {
                    sh "pwd"
                    env.COMMIT_SHA = sh(returnStdout: true, script: 'git rev-parse --short HEAD').trim()
                    sh "docker build -t ${IMAGE_NAME}:${COMMIT_SHA} ."
                }
            }
        }
        stage('Push to Docker Hub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: "${DOCKER_HUB_CREDENTIALS}", usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
                        sh "docker push ${IMAGE_NAME}:${COMMIT_SHA}"
                    }
                }
            }
        }
        stage('Update Deployment File') {
            environment {
                GIT_REPO_NAME = "angular-devops"
                GIT_USER_NAME = "TyreX6"
            }
            steps {
                withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                    sh """
                        git config user.email "ghandrisemh@gmail.com"
                        git config user.name "Ghandri Sameh"

                        # Update Helm values.yaml with new commit SHA
                        sed -i 's/tag: .*/tag: "${COMMIT_SHA}"/' helm/app/values.yaml

                        git add helm/app/values.yaml
                        git commit -m "Update deployment image to version ${COMMIT_SHA}" || echo "No changes to commit"
                        git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git HEAD:master
                    """
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
